PYTHON = python3
run:
	@pip install flask
	@pip install transformers
	@pip install pandas
	@pip install transformers
	@pip install sentence-transformers
	@pip install gensim
	@pip install nltk
	@pip install sklearn
	@pip install numpy
	@pip install torch
	@pip install networkx
	@${PYTHON} app.py
	
	
	
